name: tests

on:
  push:
    branches:
      - main
      - master
      - ci
      - test 
  pull_request:

jobs:
  systemTests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'  # 或指定特定版本，例如 '16.0'

      - name: Configure build for msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          uwp : true
          spectre : true 

          toolset: 14.41.34120
          arch: x86
          # toolset: 14.11
          # arch: amd64
      - name: Run system test 
        run: |
          .\SCons.bat source
          .\SCons.bat tests
          .\runsystemtests.bat

  unitTests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'  # 或指定特定版本，例如 '16.0'

      - name: Configure build for msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          uwp : true
          spectre : true 

          toolset: 14.41.34120
          arch: x86
          # toolset: 14.11
          # arch: amd64
      - name: Cache SCons build directory
        uses: actions/cache@v3
        with:
          path: |
            build/
            # source/lib/
          key: ${{ runner.os }}-scons-build-${{ hashFiles('**/SConstruct') }}-${{ hashFiles('**/SConscript') }}
          restore-keys: |
            ${{ runner.os }}-scons-build-


      - name: Cache python dependency directory
        uses: actions/cache@v3
        with:
          path: .venv/
          key: ${{ runner.os }}-python-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-venv-


      - name: Run unit tests 
        run: |
          .\SCons.bat -j4 tests
          .\SCons.bat -j4 source
          .\rununittests.bat

  settingsDiff:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'  # 或指定特定版本，例如 '16.0'

      - name: Configure build for msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          uwp : true
          spectre : true 

          toolset: 14.41.34120
          arch: x86
          # toolset: 14.11
          # arch: amd64
      - name: Run settings diff 
        run: |
          .\SCons.bat tests
          .\runsettingsdiff.bat
